server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率，0-1 ，1代表全采
      probability: 1


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guigu.springcloud.model

eureka:
  client:
    #是否将自己注册到eureka server上
    register-with-eureka: true
    #是否抓取注册表
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  instance:
    instance-id: payment8001
    prefer-ip-address: true   #访问路径显示IP地址
#    #Eureka 客户端向服务端发送心跳时间间隔 秒 默认30s
#    lease-renewal-interval-in-seconds: 1
#    #Eureka 服务端在收到最后一次心跳后等待时间上线 秒 默认90s
#    lease-expiration-duration-in-seconds: 2